### ISSUE TITLE
Crash shortly after displaying windows

### ISSUE THREAD

**Issue by cjfgh** [baffler/Transparent-Twitch-Chat-Overlay#232]
I am getting a crash after the two windows appeared for my main chat log and a secondary widget.  I have previously used v0.9.5, so it appears to have found the same configured windows.  But this is the message I get before it crashes in v1.0.0:

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.ArgumentException: Value does not fall within the expected range.

   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_ZoomFactor(Double ZoomFactor)

   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_ZoomFactor(Double value)

   at Microsoft.Web.WebView2.Wpf.WebView2.CoerceZoomFactorPropertyChanged(DependencyObject d, Object value)

   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)

   at Microsoft.Web.WebView2.Wpf.WebView2.set_ZoomFactor(Double value)

   at TransparentTwitchChatWPF.CustomWindow.<webView_NavigationCompleted>b__34_0()

   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.Invoke(Action callback)

   at TransparentTwitchChatWPF.CustomWindow.<webView_NavigationCompleted>d__34.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by Xs3roN** [comment]
1.0 works fine for me after updating from 0.9.4. However, 1.0.1 crashes with similar error as yours

**Comment by baffler** [comment]
Can you try [v1.0.1](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.1)? It should be fixed now

**Comment by Xs3roN** [comment]
Tried the updated installer of 1.0.1, no luck. No luck either when updated by the app ver 1.0

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Windows.Markup.XamlParseException: Wywołanie konstruktora dla typu „TransparentTwitchChatWPF.MainWindow” zgodnego z określonymi ograniczeniami wiązania spowodowało wyjątek. ---> NHotkey.HotkeyAlreadyRegisteredException: Klawisz dostępu jest już zarejestrowany. (Wyjątek od HRESULT: 0x80070581) ---> System.Runtime.InteropServices.COMException: Klawisz dostępu jest już zarejestrowany. (Wyjątek od HRESULT: 0x80070581)

   --- Koniec śladu stosu wyjątków wewnętrznych ---

   w NHotkey.Hotkey.Register(IntPtr hwnd, String name) w C:\projects\nhotkey\src\NHotkey\Hotkey.cs:wiersz 52

   w NHotkey.HotkeyManagerBase.AddOrReplace(String name, UInt32 virtualKey, HotkeyFlags flags, EventHandler`1 handler) w C:\projects\nhotkey\src\NHotkey\HotkeyManagerBase.cs:wiersz 26

   w NHotkey.Wpf.HotkeyManager.AddOrReplace(String name, Key key, ModifierKeys modifiers, EventHandler`1 handler) w C:\projects\nhotkey\src\NHotkey.Wpf\HotkeyManager.cs:wiersz 115

   w TransparentTwitchChatWPF.MainWindow.SetupOrReplaceHotkeys()

   w TransparentTwitchChatWPF.MainWindow..ctor()

   --- Koniec śladu stosu wyjątków wewnętrznych ---

   w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   w System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   w System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   w System.Windows.Application.DoStartup()

   w System.Windows.Application.<.ctor>b__1_0(Object unused)

   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   w System.Windows.Threading.DispatcherOperation.InvokeImpl()

   w System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   w MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   w MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   w System.Windows.Threading.DispatcherOperation.Invoke()

   w System.Windows.Threading.Dispatcher.ProcessQueue()

   w System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   w System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   w System.Windows.Application.RunDispatcher(Object ignore)

   w System.Windows.Application.RunInternal(Window window)

   w System.Windows.Application.Run(Window window)

   w System.Windows.Application.Run()

   w TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by baffler** [comment]
> Tried the updated installer of 1.0.1, no luck. No luck either when updated by the app ver 1.0
> ## Click on this message box and press Ctrl-C to copy the entire message
> 
> An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.
> 
> System.Windows.Markup.XamlParseException: Wywołanie konstruktora dla typu „TransparentTwitchChatWPF.MainWindow” zgodnego z określonymi ograniczeniami wiązania spowodowało wyjątek. ---> NHotkey.HotkeyAlreadyRegisteredException: 

This is fixed with [v1.0.2](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.2)

**Comment by cjfgh** [comment]
These two updates (v1.0.2) fixed all of my issues.  Thank you for the quick response!
