### ISSUE TITLE
keep getting this issue ever since redownload

### ISSUE THREAD

**Issue by Peebizzlefonizzle** [baffler/Transparent-Twitch-Chat-Overlay#24]
---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'TransparentTwitchChatWPF.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.

   at TransparentTwitchChatWPF.MainWindow..ctor()

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by jmontillo** [comment]
I have the exact same issue

**Comment by baffler** [comment]
You will most likely need to install the Visual C++ 2010 Redistributable Package. I'm pretty sure only the x86 version is needed, but you can try to install the x64 as well if it still doesn't work.

x86 version first:
http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe

x64 version if that doesn't work:
http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe

**Comment by jmontillo** [comment]
I researched and found that same solution so I tried both and it did not fix the error

**Comment by baffler** [comment]
This goes into more details about the dependencies but I will also list them out below for more clarification. https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)

The Visual C++ Redistributable Package:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

.Net Framework 4.5.2 or greater, you can get 4.7.2 here:
http://go.microsoft.com/fwlink/?linkid=863265

The list of folders and files needed to be in the same directory:

- locales (Folder)
- cef.pak
- CefSharp.BrowserSubprocess.Core.dll
- CefSharp.BrowserSubprocess.exe
- CefSharp.Core.dll
- CefSharp.Core.xml
- CefSharp.dll
- CefSharp.Wpf.dll
- CefSharp.Wpf.xml
- CefSharp.xml
- cef_100_percent.pak
- cef_200_percent.pak
- cef_extensions.pak
- chrome_elf.dll
- d3dcompiler_47.dll
- debug.log
- devtools_resources.pak
- icudtl.dat
- index.html
- Jot.dll
- libcef.dll
- libEGL.dll
- libGLESv2.dll
- natives_blob.bin
- Newtonsoft.Json.dll
- snapshot_blob.bin
- TransparentTwitchChatWPF.exe
- TransparentTwitchChatWPF.exe.config
- widevinecdmadapter.dll

And just to make sure, get the latest release if you haven't:
https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases

**Comment by jmontillo** [comment]
I installed both, restarted, still same error

**Comment by baffler** [comment]
I tried to reproduce this, I had a fresh install of Windows 10 and got the error, but the download linked fixed it. I recorded it just in case that helps: https://streamable.com/k0zc7

It would have to be some issue on your end, possibly some missing files in the folder. It's possible your antivirus may even be removing some of the dll's. Maybe that's something you can check for.

**Comment by jmontillo** [comment]
yoooo that was it.  I was going on google and searching for vc++ when I could of just used the link you gave which works (the exe one).  AWESOME!  Way better than the other overlay chat
