### ISSUE TITLE
An unhandled exception occurred

### ISSUE THREAD

**Issue by unRyker** [baffler/Transparent-Twitch-Chat-Overlay#38]
---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Exception: The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).

   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)

   at TransparentTwitchChatWPF.CustomWindow.SetCustomAddress(String url)

   at TransparentTwitchChatWPF.CustomWindow.SetupBrowser()

   at TransparentTwitchChatWPF.CustomWindow.Window_SourceInitialized(Object sender, EventArgs e)

   at System.EventHandler.Invoke(Object sender, EventArgs e)

   at System.Windows.Window.OnSourceInitialized(EventArgs e)

   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)

   at System.Windows.Window.CreateSourceWindowDuringShow()

   at System.Windows.Window.SafeCreateWindowDuringShow()

   at System.Windows.Window.ShowHelper(Object booleanBox)

   at System.Windows.Window.Show()

   at TransparentTwitchChatWPF.MainWindow.OpenNewCustomWindow(String url)

   at TransparentTwitchChatWPF.MainWindow.SetupBrowser()

   at TransparentTwitchChatWPF.MainWindow.Window_SourceInitialized(Object sender, EventArgs e)

   at System.EventHandler.Invoke(Object sender, EventArgs e)

   at System.Windows.Window.OnSourceInitialized(EventArgs e)

   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)

   at System.Windows.Window.CreateSourceWindowDuringShow()

   at System.Windows.Window.SafeCreateWindowDuringShow()

   at System.Windows.Window.ShowHelper(Object booleanBox)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------
![error](https://user-images.githubusercontent.com/26333062/92134986-31a77b80-edd8-11ea-968b-876ace06dc16.png)

This is on Windows 10, latest update and I haven't gotten an error like that with the previous version. This happens on program startup but seems to work fine when I click "Ok" and try to start it up again. I have no guesses as for what causes this issue. This does not happen every time I start it up for the first time after booting my computer.

Sidenote: Thank you for maintaining this program, I really appreciate it!

**Comment by baffler** [comment]
Not sure what could cause it but I can add a check to make sure it gets initialized first before loading the URL (which seems to be the problem here).

**Comment by baffler** [comment]
Can you try [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) and see if that fixes the issue?

**Comment by GodSponge** [comment]
I am getting this same error on the new 0.8.1. I attached the full error message.

Reverting to 0.8 does not throw this error.

[error.txt](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/files/5651664/error.txt)

**Comment by memothegreat** [comment]
i m having the exact same issue but with all latest version. (8-8.1-9) and i m guessing it s because my os is 32 bit (windows 10 pro x86)

**Comment by DerLuemmel** [comment]
Same here. Latest Version v0.9. 
[Error Message](https://pastebin.com/YresHT1e)

Restart the program will fix it for that moment.

**Comment by JuniLegends** [comment]
Hi guys.

I have install a fresh Win 10 64x and show this error...
This is different from the others.
I try install all VC++ (2008 - 2019) and none start the application.
*Sorry for bad english
[Error Mensage](https://prnt.sc/14fwels)

**Comment by baffler** [comment]
[v0.91](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.91) may have fixed this. I put in another check to make sure it loads at the appropriate time. (Kind of a hard issue to fix when I can't replicate the bug for myself)
