### ISSUE TITLE
An unhandled exception occurred.

### ISSUE THREAD

**Issue by interstate420productions** [baffler/Transparent-Twitch-Chat-Overlay#65]
[debug.log](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/files/5823436/debug.log)

**Comment by interstate420productions** [comment]
[1002/192147.205:INFO:CONSOLE(401)] "Added BTTV pro emotes for vinskinz", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192147.311:INFO:CONSOLE(401)] "Added BTTV pro emotes for bwutri", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192148.061:INFO:CONSOLE(401)] "Added BTTV pro emotes for arthiumg", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192148.846:INFO:CONSOLE(401)] "Added BTTV pro emotes for jumperow", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192149.060:INFO:CONSOLE(401)] "Added BTTV pro emotes for arthiumg", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192150.158:INFO:CONSOLE(401)] "Added BTTV pro emotes for babouska", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192150.925:INFO:CONSOLE(401)] "Added BTTV pro emotes for luvorre", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192151.472:INFO:CONSOLE(401)] "Added BTTV pro emotes for babouska", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192152.912:WARNING:angle_platform_impl.cc(45)] compileToBinary(256): 
C:\fakepath(75,10-46): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(98,10-46): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

[1002/192153.286:INFO:CONSOLE(401)] "Added BTTV pro emotes for justasian", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192154.198:INFO:CONSOLE(401)] "Added BTTV pro emotes for imthitman", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192155.872:INFO:CONSOLE(401)] "Added BTTV pro emotes for jumperow", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192159.336:INFO:CONSOLE(401)] "Added BTTV pro emotes for sidibab", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192202.691:INFO:CONSOLE(401)] "Added BTTV pro emotes for billy772", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)
[1002/192209.926:INFO:CONSOLE(401)] "Added BTTV pro emotes for jewestone", source: https://nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=xqcow&fade=false&bot_activity=False&prevent_clipping=false (401)


---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'TransparentTwitchChatWPF.MainWindow' that matches the specified binding constraints threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

   at TransparentTwitchChatWPF.MainWindow..ctor()

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by interstate420productions** [comment]
Need to install VC_Redist.xXX.exe  files for the system then it works fine.
