### ISSUE TITLE
Often crashing on launch after adding widget

### ISSUE THREAD

**Issue by Pigmess** [baffler/Transparent-Twitch-Chat-Overlay#82]
After switching my chat to a custom URL - which points to a StreamLabs "chat box" with a URL like https://streamlabs.com/widgets/chat-box/v1/numbersandletters - and adding a widget - also from StreamLabs, an "event list" with a URL like https://streamlabs.com/widgets/event-list/v1/numbersandletters - I very often see the following crash log on startup:

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.NullReferenceException: Object reference not set to an instance of an object.

   at TransparentTwitchChatWPF.App.SignalExternalCommandLineArgs(IList`1 args)

   at Microsoft.Shell.SingleInstance`1.ActivateFirstInstance(IList`1 args)

   at Microsoft.Shell.SingleInstance`1.ActivateFirstInstanceCallback(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by Pigmess** [comment]
Note, this is on 0.8 because 0.9 doesn't get past Webroot which is calling it a trojan. Any chance of clearing things up with Webroot? I think you have to specifically get it on their whitelist...

**Comment by Pigmess** [comment]
Further note - the issue stops when I remove the widget, regardless of which chat URL I use.

**Comment by baffler** [comment]
I'm not able to replicate the issue sadly. This looks like it has something to do with the app already running though, just from looking at the error message. Can you check and see if the app shows up in your running processes when this error occurs?
