### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by Miizaa** [baffler/Transparent-Twitch-Chat-Overlay#93]
Hello everyone, I've formatted my PC some days ago, since then I got this error below everytime I try to start Transparent chat:

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Windows.Markup.XamlParseException: A invocação do construtor no tipo 'TransparentTwitchChatWPF.MainWindow' que corresponde às restrições de associação especificadas iniciou uma exceção. ---> System.IO.FileNotFoundException: Não foi possível carregar arquivo ou assembly 'CefSharp.Core.dll' ou uma de suas dependências. Não foi possível encontrar o módulo especificado.

   em TransparentTwitchChatWPF.MainWindow..ctor()

   --- Fim do rastreamento de pilha de exceções internas ---

   em System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   em System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   em System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   em System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   em System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   em System.Windows.Application.DoStartup()

   em System.Windows.Application.<.ctor>b__1_0(Object unused)

   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   em System.Windows.Threading.DispatcherOperation.InvokeImpl()

   em System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   em System.Windows.Threading.DispatcherOperation.Invoke()

   em System.Windows.Threading.Dispatcher.ProcessQueue()

   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   em System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   em System.Windows.Application.RunDispatcher(Object ignore)

   em System.Windows.Application.RunInternal(Window window)

   em System.Windows.Application.Run(Window window)

   em System.Windows.Application.Run()

   em TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/19503976/123710880-dd2d2b00-d845-11eb-96c5-5ad1efcb86bc.png)

Does anyone know what's wrong?

**Comment by jet082** [comment]
Same issue here.

**Comment by ImAFreakenCyborg** [comment]
I am having the same issue. This overlay helps a lot with managing chat with my disabilities, here is what mine says:

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Exception: The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized (CefLifeSpanHandler::OnAfterCreated).

   at CefSharp.Wpf.ChromiumWebBrowser.Load(String url)

   at TransparentTwitchChatWPF.CustomWindow.SetCustomAddress(String url)

   at TransparentTwitchChatWPF.CustomWindow.SetupBrowser()

   at TransparentTwitchChatWPF.CustomWindow.Window_Loaded(Object sender, RoutedEventArgs e)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)

   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)

   at MS.Internal.LoadedOrUnloadedOperation.DoWork()

   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()

   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)

   at System.Windows.Interop.HwndTarget.OnResize()

   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
---------------------------
OK   
---------------------------

**Comment by baffler** [comment]
I believe these are separate issues. The first issue posted seems to be possibly missing a DLL file or more likely, you need to install VC++ runtime. I would suggest to uninstall the current version and then go to the [releases page](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases) and make sure you download the installer. This should fix the issue for that.

@ImAFreakenCyborg Your issue seems to be a bug with custom URL window for the widgets. I'll see if I can get this issue fixed with the next update which will be releasing soon 👍

**Comment by baffler** [comment]
@ImAFreakenCyborg Can you try [v0.91](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.91)?

**Comment by boisvenu** [comment]
Any thoughts on this similar error I am having?

---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.UnauthorizedAccessException: Access to the path 'C:\Users\vendo\AppData\Roaming\TransparentTwitchChatWPF\MainWindow_State.json' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)

   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)

   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)

   at System.IO.File.WriteAllText(String path, String contents)

   at Jot.Storage.Stores.JsonFileStore.SaveValues(Dictionary`2 values)

   at Jot.Storage.PersistentStoreBase.CommitChanges()

   at Jot.TrackingConfiguration.Persist()

   at Jot.TrackingConfiguration.<RegisterPersistTrigger>b__61_1()

   at lambda_method(Closure , Object , EventArgs )

   at System.Windows.Window.OnLocationChanged(EventArgs e)

   at System.Windows.Window.WmMoveChangedHelper()

   at System.Windows.Window.WmMoveChanged()

   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
---------------------------
OK   
---------------------------
